#ifndef DEFINES_H_

#include "stm32g030xx.h"

#define CPU_FREQ 64000000UL


#define FLASH_ACR_LATENCY_0WS (0UL << FLASH_ACR_LATENCY_Pos)
#define FLASH_ACR_LATENCY_1WS (1UL << FLASH_ACR_LATENCY_Pos)
#define FLASH_ACR_LATENCY_2WS (2UL << FLASH_ACR_LATENCY_Pos)

#define RCC_CFGR_SW_HSISYS (0)
#define RCC_CFGR_SW_HSE (RCC_CFGR_SW_0)
#define RCC_CFGR_SW_PLLRCLK (RCC_CFGR_SW_1)
#define RCC_CFGR_SW_LSI (RCC_CFGR_SW_1 | RCC_CFGR_SW_0)
#define RCC_CFGR_SW_LSE (RCC_CFGR_SW_2)

#define RCC_PLLCFGR_PLLR_Val(n) (((uint32_t)(n) - 1) << RCC_PLLCFGR_PLLR_Pos)
#define RCC_PLLCFGR_PLLN_Val(n) (((uint32_t)(n)) << RCC_PLLCFGR_PLLN_Pos)
#define RCC_PLLCFGR_PLLM_Val(n) (((uint32_t)(n) - 1) << RCC_PLLCFGR_PLLM_Pos)

#define TIM_CCMR1_CC1S_OUTPUT (0 << TIM_CCMR1_CC1S_Pos)
#define TIM_CCMR1_CC2S_OUTPUT (0 << TIM_CCMR1_CC2S_Pos)
#define TIM_CCMR1_OC1M_PWM1 (TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1)
#define TIM_CCMR1_OC1M_PWM2 (TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_0)
#define TIM_CCMR1_OC2M_PWM1 (TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1)
#define TIM_CCMR1_OC2M_PWM2 (TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_0)

#define TIM_DCR_DBA_ARR  (11UL << TIM_DCR_DBA_Pos)
#define TIM_DCR_DBA_RCR  (12UL << TIM_DCR_DBA_Pos)
#define TIM_DCR_DBA_CCR1 (13UL << TIM_DCR_DBA_Pos)
#define TIM_DCR_DBA_CCR2 (14UL << TIM_DCR_DBA_Pos)

#define TIM_DCR_DBL_Val(n) (((uint32_t)(n) - 1) << TIM_DCR_DBL_Pos)

#define DMAMUX_CCR_REQ_TIM1_UP 25
#define DMAMUX_CCR_REQ_USART2_TX 53

#define GPIOA_AFR0_PA2_UART2_TX   (1UL << 8)
#define GPIOA_AFR0_PA3_UART2_RX   (1UL << 12)
#define GPIOA_AFR0_PA5_SPI1_SCK   (0UL << 20)
#define GPIOA_AFR0_PA6_SPI1_MISO  (0UL << 24)
#define GPIOA_AFR0_PA7_SPI1_MOSI  (0UL << 28)

#define GPIOA_AFR1_PA8_TIM1_CH1   (2UL << 0)
#define GPIOA_AFR1_PA9_TIM1_CH2   (2UL << 4)
#define GPIOA_AFR1_PA13_SWDIO     (0UL << 20)
#define GPIOA_AFR1_PA14_SWCLK     (0UL << 24)

#define GPIO_MODER_INPUT  0x0UL
#define GPIO_MODER_OUTPUT 0x1UL
#define GPIO_MODER_AF     0x2UL
#define GPIO_MODER_ANALOG 0x3UL
#define GPIO_MODER_MASK   0x3UL

#define GPIO_OTYPER_PP 0x0UL
#define GPIO_OTYPER_OD 0x1UL

#define GPIO_OSPEEDR_LOW 0x0UL
#define GPIO_OSPEEDR_MID 0x1UL
#define GPIO_OSPEEDR_HI  0x2UL
#define GPIO_OSPEEDR_VHI 0x3UL

#define GPIO_PUPDR_NONE 0x00
#define GPIO_PUPDR_PU   0x01
#define GPIO_PUPDR_PD   0x02

#define DMA_CCR_DIR_MEMORY_TO_PERIPH DMA_CCR_DIR
#define DMA_CCR_DIR_PERIPH_TO_MEMORY 0

#define DMA_CCR_MSIZE_8BITS 0
#define DMA_CCR_MSIZE_16BITS DMA_CCR_MSIZE_0
#define DMA_CCR_MSIZE_32BITS DMA_CCR_MSIZE_1

#define DMA_CCR_PSIZE_8BITS 0
#define DMA_CCR_PSIZE_16BITS DMA_CCR_PSIZE_0
#define DMA_CCR_PSIZE_32BITS DMA_CCR_PSIZE_1

#endif
